#!/bin/bash

# iOS App Setup Script
# This script extracts the iOS demo app from the zip file

echo "iOS App Setup Guide"
echo "==================="
echo ""
echo "The iOS app files in apps/ios/ are placeholders."
echo "You need to download the actual iOS demo app."
echo ""
echo "Steps to setup iOS testing:"
echo ""
echo "1. Download the iOS Simulator app:"
echo "   https://github.com/webdriverio/native-demo-app/releases/latest"
echo ""
echo "2. Look for: iOS-Simulator-NativeDemoApp-x.x.x.app.zip"
echo "   (Get the latest version)"
echo ""
echo "3. Extract the downloaded file:"
echo "   cd apps/ios"
echo "   unzip ~/Downloads/iOS-Simulator-NativeDemoApp-x.x.x.app.zip"
echo ""
echo "4. Update wdio.ios.conf.ts:"
echo "   - Uncomment the 'appium:app' line"
echo "   - Update with the actual .app file name"
echo "   - Comment out 'appium:bundleId' line"
echo ""
echo "5. Run iOS tests:"
echo "   npm run test:ios"
echo ""
echo "Alternative: Use bundleId (current config)"
echo "   - App must be pre-installed on iOS simulator"
echo "   - No file download needed"
echo "   - May not work for first-time setup"
echo ""
